// Code generated by ent, DO NOT EDIT.

package accountquotashareusage

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the accountquotashareusage type in the database.
	Label = "account_quota_share_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldWindowKind holds the string denoting the window_kind field in the database.
	FieldWindowKind = "window_kind"
	// FieldResetAt holds the string denoting the reset_at field in the database.
	FieldResetAt = "reset_at"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the accountquotashareusage in the database.
	Table = "account_quota_share_usages"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "account_quota_share_usages"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for accountquotashareusage fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldWindowKind,
	FieldResetAt,
	FieldCost,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// WindowKindValidator is a validator for the "window_kind" field. It is called by the builders before save.
	WindowKindValidator func(string) error
	// DefaultCost holds the default value on creation for the "cost" field.
	DefaultCost float64
)

// OrderOption defines the ordering options for the AccountQuotaShareUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByWindowKind orders the results by the window_kind field.
func ByWindowKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowKind, opts...).ToFunc()
}

// ByResetAt orders the results by the reset_at field.
func ByResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetAt, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
