// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountuserquotashare"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountUserQuotaShareCreate is the builder for creating a AccountUserQuotaShare entity.
type AccountUserQuotaShareCreate struct {
	config
	mutation *AccountUserQuotaShareMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountUserQuotaShareCreate) SetCreatedAt(v time.Time) *AccountUserQuotaShareCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountUserQuotaShareCreate) SetNillableCreatedAt(v *time.Time) *AccountUserQuotaShareCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountUserQuotaShareCreate) SetUpdatedAt(v time.Time) *AccountUserQuotaShareCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountUserQuotaShareCreate) SetNillableUpdatedAt(v *time.Time) *AccountUserQuotaShareCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AccountUserQuotaShareCreate) SetDeletedAt(v time.Time) *AccountUserQuotaShareCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AccountUserQuotaShareCreate) SetNillableDeletedAt(v *time.Time) *AccountUserQuotaShareCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountUserQuotaShareCreate) SetAccountID(v int64) *AccountUserQuotaShareCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountUserQuotaShareCreate) SetUserID(v int64) *AccountUserQuotaShareCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFiveHourPercent sets the "five_hour_percent" field.
func (_c *AccountUserQuotaShareCreate) SetFiveHourPercent(v float64) *AccountUserQuotaShareCreate {
	_c.mutation.SetFiveHourPercent(v)
	return _c
}

// SetNillableFiveHourPercent sets the "five_hour_percent" field if the given value is not nil.
func (_c *AccountUserQuotaShareCreate) SetNillableFiveHourPercent(v *float64) *AccountUserQuotaShareCreate {
	if v != nil {
		_c.SetFiveHourPercent(*v)
	}
	return _c
}

// SetSevenDayPercent sets the "seven_day_percent" field.
func (_c *AccountUserQuotaShareCreate) SetSevenDayPercent(v float64) *AccountUserQuotaShareCreate {
	_c.mutation.SetSevenDayPercent(v)
	return _c
}

// SetNillableSevenDayPercent sets the "seven_day_percent" field if the given value is not nil.
func (_c *AccountUserQuotaShareCreate) SetNillableSevenDayPercent(v *float64) *AccountUserQuotaShareCreate {
	if v != nil {
		_c.SetSevenDayPercent(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountUserQuotaShareCreate) SetAccount(v *Account) *AccountUserQuotaShareCreate {
	return _c.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccountUserQuotaShareCreate) SetUser(v *User) *AccountUserQuotaShareCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AccountUserQuotaShareMutation object of the builder.
func (_c *AccountUserQuotaShareCreate) Mutation() *AccountUserQuotaShareMutation {
	return _c.mutation
}

// Save creates the AccountUserQuotaShare in the database.
func (_c *AccountUserQuotaShareCreate) Save(ctx context.Context) (*AccountUserQuotaShare, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountUserQuotaShareCreate) SaveX(ctx context.Context) *AccountUserQuotaShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUserQuotaShareCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUserQuotaShareCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountUserQuotaShareCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if accountuserquotashare.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized accountuserquotashare.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := accountuserquotashare.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if accountuserquotashare.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized accountuserquotashare.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := accountuserquotashare.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.FiveHourPercent(); !ok {
		v := accountuserquotashare.DefaultFiveHourPercent
		_c.mutation.SetFiveHourPercent(v)
	}
	if _, ok := _c.mutation.SevenDayPercent(); !ok {
		v := accountuserquotashare.DefaultSevenDayPercent
		_c.mutation.SetSevenDayPercent(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountUserQuotaShareCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountUserQuotaShare.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountUserQuotaShare.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountUserQuotaShare.account_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AccountUserQuotaShare.user_id"`)}
	}
	if _, ok := _c.mutation.FiveHourPercent(); !ok {
		return &ValidationError{Name: "five_hour_percent", err: errors.New(`ent: missing required field "AccountUserQuotaShare.five_hour_percent"`)}
	}
	if _, ok := _c.mutation.SevenDayPercent(); !ok {
		return &ValidationError{Name: "seven_day_percent", err: errors.New(`ent: missing required field "AccountUserQuotaShare.seven_day_percent"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountUserQuotaShare.account"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AccountUserQuotaShare.user"`)}
	}
	return nil
}

func (_c *AccountUserQuotaShareCreate) sqlSave(ctx context.Context) (*AccountUserQuotaShare, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountUserQuotaShareCreate) createSpec() (*AccountUserQuotaShare, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountUserQuotaShare{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountuserquotashare.Table, sqlgraph.NewFieldSpec(accountuserquotashare.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountuserquotashare.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountuserquotashare.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(accountuserquotashare.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.FiveHourPercent(); ok {
		_spec.SetField(accountuserquotashare.FieldFiveHourPercent, field.TypeFloat64, value)
		_node.FiveHourPercent = value
	}
	if value, ok := _c.mutation.SevenDayPercent(); ok {
		_spec.SetField(accountuserquotashare.FieldSevenDayPercent, field.TypeFloat64, value)
		_node.SevenDayPercent = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.AccountTable,
			Columns: []string{accountuserquotashare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.UserTable,
			Columns: []string{accountuserquotashare.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUserQuotaShare.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUserQuotaShareUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUserQuotaShareCreate) OnConflict(opts ...sql.ConflictOption) *AccountUserQuotaShareUpsertOne {
	_c.conflict = opts
	return &AccountUserQuotaShareUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUserQuotaShare.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUserQuotaShareCreate) OnConflictColumns(columns ...string) *AccountUserQuotaShareUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUserQuotaShareUpsertOne{
		create: _c,
	}
}

type (
	// AccountUserQuotaShareUpsertOne is the builder for "upsert"-ing
	//  one AccountUserQuotaShare node.
	AccountUserQuotaShareUpsertOne struct {
		create *AccountUserQuotaShareCreate
	}

	// AccountUserQuotaShareUpsert is the "OnConflict" setter.
	AccountUserQuotaShareUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUserQuotaShareUpsert) SetUpdatedAt(v time.Time) *AccountUserQuotaShareUpsert {
	u.Set(accountuserquotashare.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsert) UpdateUpdatedAt() *AccountUserQuotaShareUpsert {
	u.SetExcluded(accountuserquotashare.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AccountUserQuotaShareUpsert) SetDeletedAt(v time.Time) *AccountUserQuotaShareUpsert {
	u.Set(accountuserquotashare.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsert) UpdateDeletedAt() *AccountUserQuotaShareUpsert {
	u.SetExcluded(accountuserquotashare.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AccountUserQuotaShareUpsert) ClearDeletedAt() *AccountUserQuotaShareUpsert {
	u.SetNull(accountuserquotashare.FieldDeletedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountUserQuotaShareUpsert) SetAccountID(v int64) *AccountUserQuotaShareUpsert {
	u.Set(accountuserquotashare.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsert) UpdateAccountID() *AccountUserQuotaShareUpsert {
	u.SetExcluded(accountuserquotashare.FieldAccountID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountUserQuotaShareUpsert) SetUserID(v int64) *AccountUserQuotaShareUpsert {
	u.Set(accountuserquotashare.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsert) UpdateUserID() *AccountUserQuotaShareUpsert {
	u.SetExcluded(accountuserquotashare.FieldUserID)
	return u
}

// SetFiveHourPercent sets the "five_hour_percent" field.
func (u *AccountUserQuotaShareUpsert) SetFiveHourPercent(v float64) *AccountUserQuotaShareUpsert {
	u.Set(accountuserquotashare.FieldFiveHourPercent, v)
	return u
}

// UpdateFiveHourPercent sets the "five_hour_percent" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsert) UpdateFiveHourPercent() *AccountUserQuotaShareUpsert {
	u.SetExcluded(accountuserquotashare.FieldFiveHourPercent)
	return u
}

// AddFiveHourPercent adds v to the "five_hour_percent" field.
func (u *AccountUserQuotaShareUpsert) AddFiveHourPercent(v float64) *AccountUserQuotaShareUpsert {
	u.Add(accountuserquotashare.FieldFiveHourPercent, v)
	return u
}

// SetSevenDayPercent sets the "seven_day_percent" field.
func (u *AccountUserQuotaShareUpsert) SetSevenDayPercent(v float64) *AccountUserQuotaShareUpsert {
	u.Set(accountuserquotashare.FieldSevenDayPercent, v)
	return u
}

// UpdateSevenDayPercent sets the "seven_day_percent" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsert) UpdateSevenDayPercent() *AccountUserQuotaShareUpsert {
	u.SetExcluded(accountuserquotashare.FieldSevenDayPercent)
	return u
}

// AddSevenDayPercent adds v to the "seven_day_percent" field.
func (u *AccountUserQuotaShareUpsert) AddSevenDayPercent(v float64) *AccountUserQuotaShareUpsert {
	u.Add(accountuserquotashare.FieldSevenDayPercent, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountUserQuotaShare.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUserQuotaShareUpsertOne) UpdateNewValues() *AccountUserQuotaShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountuserquotashare.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUserQuotaShare.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUserQuotaShareUpsertOne) Ignore() *AccountUserQuotaShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUserQuotaShareUpsertOne) DoNothing() *AccountUserQuotaShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUserQuotaShareCreate.OnConflict
// documentation for more info.
func (u *AccountUserQuotaShareUpsertOne) Update(set func(*AccountUserQuotaShareUpsert)) *AccountUserQuotaShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUserQuotaShareUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUserQuotaShareUpsertOne) SetUpdatedAt(v time.Time) *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertOne) UpdateUpdatedAt() *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AccountUserQuotaShareUpsertOne) SetDeletedAt(v time.Time) *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertOne) UpdateDeletedAt() *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AccountUserQuotaShareUpsertOne) ClearDeletedAt() *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.ClearDeletedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountUserQuotaShareUpsertOne) SetAccountID(v int64) *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertOne) UpdateAccountID() *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUserQuotaShareUpsertOne) SetUserID(v int64) *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertOne) UpdateUserID() *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateUserID()
	})
}

// SetFiveHourPercent sets the "five_hour_percent" field.
func (u *AccountUserQuotaShareUpsertOne) SetFiveHourPercent(v float64) *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetFiveHourPercent(v)
	})
}

// AddFiveHourPercent adds v to the "five_hour_percent" field.
func (u *AccountUserQuotaShareUpsertOne) AddFiveHourPercent(v float64) *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.AddFiveHourPercent(v)
	})
}

// UpdateFiveHourPercent sets the "five_hour_percent" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertOne) UpdateFiveHourPercent() *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateFiveHourPercent()
	})
}

// SetSevenDayPercent sets the "seven_day_percent" field.
func (u *AccountUserQuotaShareUpsertOne) SetSevenDayPercent(v float64) *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetSevenDayPercent(v)
	})
}

// AddSevenDayPercent adds v to the "seven_day_percent" field.
func (u *AccountUserQuotaShareUpsertOne) AddSevenDayPercent(v float64) *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.AddSevenDayPercent(v)
	})
}

// UpdateSevenDayPercent sets the "seven_day_percent" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertOne) UpdateSevenDayPercent() *AccountUserQuotaShareUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateSevenDayPercent()
	})
}

// Exec executes the query.
func (u *AccountUserQuotaShareUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUserQuotaShareCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUserQuotaShareUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUserQuotaShareUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUserQuotaShareUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountUserQuotaShareCreateBulk is the builder for creating many AccountUserQuotaShare entities in bulk.
type AccountUserQuotaShareCreateBulk struct {
	config
	err      error
	builders []*AccountUserQuotaShareCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountUserQuotaShare entities in the database.
func (_c *AccountUserQuotaShareCreateBulk) Save(ctx context.Context) ([]*AccountUserQuotaShare, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountUserQuotaShare, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountUserQuotaShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountUserQuotaShareCreateBulk) SaveX(ctx context.Context) []*AccountUserQuotaShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUserQuotaShareCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUserQuotaShareCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUserQuotaShare.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUserQuotaShareUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUserQuotaShareCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUserQuotaShareUpsertBulk {
	_c.conflict = opts
	return &AccountUserQuotaShareUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUserQuotaShare.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUserQuotaShareCreateBulk) OnConflictColumns(columns ...string) *AccountUserQuotaShareUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUserQuotaShareUpsertBulk{
		create: _c,
	}
}

// AccountUserQuotaShareUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountUserQuotaShare nodes.
type AccountUserQuotaShareUpsertBulk struct {
	create *AccountUserQuotaShareCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountUserQuotaShare.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUserQuotaShareUpsertBulk) UpdateNewValues() *AccountUserQuotaShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountuserquotashare.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUserQuotaShare.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUserQuotaShareUpsertBulk) Ignore() *AccountUserQuotaShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUserQuotaShareUpsertBulk) DoNothing() *AccountUserQuotaShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUserQuotaShareCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUserQuotaShareUpsertBulk) Update(set func(*AccountUserQuotaShareUpsert)) *AccountUserQuotaShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUserQuotaShareUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUserQuotaShareUpsertBulk) SetUpdatedAt(v time.Time) *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertBulk) UpdateUpdatedAt() *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AccountUserQuotaShareUpsertBulk) SetDeletedAt(v time.Time) *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertBulk) UpdateDeletedAt() *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AccountUserQuotaShareUpsertBulk) ClearDeletedAt() *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.ClearDeletedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountUserQuotaShareUpsertBulk) SetAccountID(v int64) *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertBulk) UpdateAccountID() *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUserQuotaShareUpsertBulk) SetUserID(v int64) *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertBulk) UpdateUserID() *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateUserID()
	})
}

// SetFiveHourPercent sets the "five_hour_percent" field.
func (u *AccountUserQuotaShareUpsertBulk) SetFiveHourPercent(v float64) *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetFiveHourPercent(v)
	})
}

// AddFiveHourPercent adds v to the "five_hour_percent" field.
func (u *AccountUserQuotaShareUpsertBulk) AddFiveHourPercent(v float64) *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.AddFiveHourPercent(v)
	})
}

// UpdateFiveHourPercent sets the "five_hour_percent" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertBulk) UpdateFiveHourPercent() *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateFiveHourPercent()
	})
}

// SetSevenDayPercent sets the "seven_day_percent" field.
func (u *AccountUserQuotaShareUpsertBulk) SetSevenDayPercent(v float64) *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.SetSevenDayPercent(v)
	})
}

// AddSevenDayPercent adds v to the "seven_day_percent" field.
func (u *AccountUserQuotaShareUpsertBulk) AddSevenDayPercent(v float64) *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.AddSevenDayPercent(v)
	})
}

// UpdateSevenDayPercent sets the "seven_day_percent" field to the value that was provided on create.
func (u *AccountUserQuotaShareUpsertBulk) UpdateSevenDayPercent() *AccountUserQuotaShareUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUpsert) {
		s.UpdateSevenDayPercent()
	})
}

// Exec executes the query.
func (u *AccountUserQuotaShareUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountUserQuotaShareCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUserQuotaShareCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUserQuotaShareUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
