// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountuserquotashareusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountUserQuotaShareUsageCreate is the builder for creating a AccountUserQuotaShareUsage entity.
type AccountUserQuotaShareUsageCreate struct {
	config
	mutation *AccountUserQuotaShareUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountUserQuotaShareUsageCreate) SetAccountID(v int64) *AccountUserQuotaShareUsageCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountUserQuotaShareUsageCreate) SetUserID(v int64) *AccountUserQuotaShareUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetWindowKind sets the "window_kind" field.
func (_c *AccountUserQuotaShareUsageCreate) SetWindowKind(v string) *AccountUserQuotaShareUsageCreate {
	_c.mutation.SetWindowKind(v)
	return _c
}

// SetResetAt sets the "reset_at" field.
func (_c *AccountUserQuotaShareUsageCreate) SetResetAt(v time.Time) *AccountUserQuotaShareUsageCreate {
	_c.mutation.SetResetAt(v)
	return _c
}

// SetCost sets the "cost" field.
func (_c *AccountUserQuotaShareUsageCreate) SetCost(v float64) *AccountUserQuotaShareUsageCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *AccountUserQuotaShareUsageCreate) SetNillableCost(v *float64) *AccountUserQuotaShareUsageCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountUserQuotaShareUsageCreate) SetAccount(v *Account) *AccountUserQuotaShareUsageCreate {
	return _c.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccountUserQuotaShareUsageCreate) SetUser(v *User) *AccountUserQuotaShareUsageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AccountUserQuotaShareUsageMutation object of the builder.
func (_c *AccountUserQuotaShareUsageCreate) Mutation() *AccountUserQuotaShareUsageMutation {
	return _c.mutation
}

// Save creates the AccountUserQuotaShareUsage in the database.
func (_c *AccountUserQuotaShareUsageCreate) Save(ctx context.Context) (*AccountUserQuotaShareUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountUserQuotaShareUsageCreate) SaveX(ctx context.Context) *AccountUserQuotaShareUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUserQuotaShareUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUserQuotaShareUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountUserQuotaShareUsageCreate) defaults() {
	if _, ok := _c.mutation.Cost(); !ok {
		v := accountuserquotashareusage.DefaultCost
		_c.mutation.SetCost(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountUserQuotaShareUsageCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountUserQuotaShareUsage.account_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AccountUserQuotaShareUsage.user_id"`)}
	}
	if _, ok := _c.mutation.WindowKind(); !ok {
		return &ValidationError{Name: "window_kind", err: errors.New(`ent: missing required field "AccountUserQuotaShareUsage.window_kind"`)}
	}
	if v, ok := _c.mutation.WindowKind(); ok {
		if err := accountuserquotashareusage.WindowKindValidator(v); err != nil {
			return &ValidationError{Name: "window_kind", err: fmt.Errorf(`ent: validator failed for field "AccountUserQuotaShareUsage.window_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResetAt(); !ok {
		return &ValidationError{Name: "reset_at", err: errors.New(`ent: missing required field "AccountUserQuotaShareUsage.reset_at"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "AccountUserQuotaShareUsage.cost"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountUserQuotaShareUsage.account"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AccountUserQuotaShareUsage.user"`)}
	}
	return nil
}

func (_c *AccountUserQuotaShareUsageCreate) sqlSave(ctx context.Context) (*AccountUserQuotaShareUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountUserQuotaShareUsageCreate) createSpec() (*AccountUserQuotaShareUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountUserQuotaShareUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountuserquotashareusage.Table, sqlgraph.NewFieldSpec(accountuserquotashareusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.WindowKind(); ok {
		_spec.SetField(accountuserquotashareusage.FieldWindowKind, field.TypeString, value)
		_node.WindowKind = value
	}
	if value, ok := _c.mutation.ResetAt(); ok {
		_spec.SetField(accountuserquotashareusage.FieldResetAt, field.TypeTime, value)
		_node.ResetAt = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(accountuserquotashareusage.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.AccountTable,
			Columns: []string{accountuserquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.UserTable,
			Columns: []string{accountuserquotashareusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUserQuotaShareUsage.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUserQuotaShareUsageUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUserQuotaShareUsageCreate) OnConflict(opts ...sql.ConflictOption) *AccountUserQuotaShareUsageUpsertOne {
	_c.conflict = opts
	return &AccountUserQuotaShareUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUserQuotaShareUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUserQuotaShareUsageCreate) OnConflictColumns(columns ...string) *AccountUserQuotaShareUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUserQuotaShareUsageUpsertOne{
		create: _c,
	}
}

type (
	// AccountUserQuotaShareUsageUpsertOne is the builder for "upsert"-ing
	//  one AccountUserQuotaShareUsage node.
	AccountUserQuotaShareUsageUpsertOne struct {
		create *AccountUserQuotaShareUsageCreate
	}

	// AccountUserQuotaShareUsageUpsert is the "OnConflict" setter.
	AccountUserQuotaShareUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountUserQuotaShareUsageUpsert) SetAccountID(v int64) *AccountUserQuotaShareUsageUpsert {
	u.Set(accountuserquotashareusage.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsert) UpdateAccountID() *AccountUserQuotaShareUsageUpsert {
	u.SetExcluded(accountuserquotashareusage.FieldAccountID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountUserQuotaShareUsageUpsert) SetUserID(v int64) *AccountUserQuotaShareUsageUpsert {
	u.Set(accountuserquotashareusage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsert) UpdateUserID() *AccountUserQuotaShareUsageUpsert {
	u.SetExcluded(accountuserquotashareusage.FieldUserID)
	return u
}

// SetWindowKind sets the "window_kind" field.
func (u *AccountUserQuotaShareUsageUpsert) SetWindowKind(v string) *AccountUserQuotaShareUsageUpsert {
	u.Set(accountuserquotashareusage.FieldWindowKind, v)
	return u
}

// UpdateWindowKind sets the "window_kind" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsert) UpdateWindowKind() *AccountUserQuotaShareUsageUpsert {
	u.SetExcluded(accountuserquotashareusage.FieldWindowKind)
	return u
}

// SetResetAt sets the "reset_at" field.
func (u *AccountUserQuotaShareUsageUpsert) SetResetAt(v time.Time) *AccountUserQuotaShareUsageUpsert {
	u.Set(accountuserquotashareusage.FieldResetAt, v)
	return u
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsert) UpdateResetAt() *AccountUserQuotaShareUsageUpsert {
	u.SetExcluded(accountuserquotashareusage.FieldResetAt)
	return u
}

// SetCost sets the "cost" field.
func (u *AccountUserQuotaShareUsageUpsert) SetCost(v float64) *AccountUserQuotaShareUsageUpsert {
	u.Set(accountuserquotashareusage.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsert) UpdateCost() *AccountUserQuotaShareUsageUpsert {
	u.SetExcluded(accountuserquotashareusage.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *AccountUserQuotaShareUsageUpsert) AddCost(v float64) *AccountUserQuotaShareUsageUpsert {
	u.Add(accountuserquotashareusage.FieldCost, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountUserQuotaShareUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUserQuotaShareUsageUpsertOne) UpdateNewValues() *AccountUserQuotaShareUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUserQuotaShareUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUserQuotaShareUsageUpsertOne) Ignore() *AccountUserQuotaShareUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUserQuotaShareUsageUpsertOne) DoNothing() *AccountUserQuotaShareUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUserQuotaShareUsageCreate.OnConflict
// documentation for more info.
func (u *AccountUserQuotaShareUsageUpsertOne) Update(set func(*AccountUserQuotaShareUsageUpsert)) *AccountUserQuotaShareUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUserQuotaShareUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountUserQuotaShareUsageUpsertOne) SetAccountID(v int64) *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertOne) UpdateAccountID() *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUserQuotaShareUsageUpsertOne) SetUserID(v int64) *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertOne) UpdateUserID() *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetWindowKind sets the "window_kind" field.
func (u *AccountUserQuotaShareUsageUpsertOne) SetWindowKind(v string) *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetWindowKind(v)
	})
}

// UpdateWindowKind sets the "window_kind" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertOne) UpdateWindowKind() *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateWindowKind()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *AccountUserQuotaShareUsageUpsertOne) SetResetAt(v time.Time) *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertOne) UpdateResetAt() *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateResetAt()
	})
}

// SetCost sets the "cost" field.
func (u *AccountUserQuotaShareUsageUpsertOne) SetCost(v float64) *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *AccountUserQuotaShareUsageUpsertOne) AddCost(v float64) *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertOne) UpdateCost() *AccountUserQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateCost()
	})
}

// Exec executes the query.
func (u *AccountUserQuotaShareUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUserQuotaShareUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUserQuotaShareUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUserQuotaShareUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUserQuotaShareUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountUserQuotaShareUsageCreateBulk is the builder for creating many AccountUserQuotaShareUsage entities in bulk.
type AccountUserQuotaShareUsageCreateBulk struct {
	config
	err      error
	builders []*AccountUserQuotaShareUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountUserQuotaShareUsage entities in the database.
func (_c *AccountUserQuotaShareUsageCreateBulk) Save(ctx context.Context) ([]*AccountUserQuotaShareUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountUserQuotaShareUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountUserQuotaShareUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountUserQuotaShareUsageCreateBulk) SaveX(ctx context.Context) []*AccountUserQuotaShareUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUserQuotaShareUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUserQuotaShareUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUserQuotaShareUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUserQuotaShareUsageUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUserQuotaShareUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUserQuotaShareUsageUpsertBulk {
	_c.conflict = opts
	return &AccountUserQuotaShareUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUserQuotaShareUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUserQuotaShareUsageCreateBulk) OnConflictColumns(columns ...string) *AccountUserQuotaShareUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUserQuotaShareUsageUpsertBulk{
		create: _c,
	}
}

// AccountUserQuotaShareUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountUserQuotaShareUsage nodes.
type AccountUserQuotaShareUsageUpsertBulk struct {
	create *AccountUserQuotaShareUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountUserQuotaShareUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUserQuotaShareUsageUpsertBulk) UpdateNewValues() *AccountUserQuotaShareUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUserQuotaShareUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUserQuotaShareUsageUpsertBulk) Ignore() *AccountUserQuotaShareUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUserQuotaShareUsageUpsertBulk) DoNothing() *AccountUserQuotaShareUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUserQuotaShareUsageCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUserQuotaShareUsageUpsertBulk) Update(set func(*AccountUserQuotaShareUsageUpsert)) *AccountUserQuotaShareUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUserQuotaShareUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountUserQuotaShareUsageUpsertBulk) SetAccountID(v int64) *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertBulk) UpdateAccountID() *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUserQuotaShareUsageUpsertBulk) SetUserID(v int64) *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertBulk) UpdateUserID() *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetWindowKind sets the "window_kind" field.
func (u *AccountUserQuotaShareUsageUpsertBulk) SetWindowKind(v string) *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetWindowKind(v)
	})
}

// UpdateWindowKind sets the "window_kind" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertBulk) UpdateWindowKind() *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateWindowKind()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *AccountUserQuotaShareUsageUpsertBulk) SetResetAt(v time.Time) *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertBulk) UpdateResetAt() *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateResetAt()
	})
}

// SetCost sets the "cost" field.
func (u *AccountUserQuotaShareUsageUpsertBulk) SetCost(v float64) *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *AccountUserQuotaShareUsageUpsertBulk) AddCost(v float64) *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *AccountUserQuotaShareUsageUpsertBulk) UpdateCost() *AccountUserQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountUserQuotaShareUsageUpsert) {
		s.UpdateCost()
	})
}

// Exec executes the query.
func (u *AccountUserQuotaShareUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountUserQuotaShareUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUserQuotaShareUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUserQuotaShareUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
