// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountuserquotashareusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountUserQuotaShareUsageUpdate is the builder for updating AccountUserQuotaShareUsage entities.
type AccountUserQuotaShareUsageUpdate struct {
	config
	hooks    []Hook
	mutation *AccountUserQuotaShareUsageMutation
}

// Where appends a list predicates to the AccountUserQuotaShareUsageUpdate builder.
func (_u *AccountUserQuotaShareUsageUpdate) Where(ps ...predicate.AccountUserQuotaShareUsage) *AccountUserQuotaShareUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUserQuotaShareUsageUpdate) SetAccountID(v int64) *AccountUserQuotaShareUsageUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdate) SetNillableAccountID(v *int64) *AccountUserQuotaShareUsageUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountUserQuotaShareUsageUpdate) SetUserID(v int64) *AccountUserQuotaShareUsageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdate) SetNillableUserID(v *int64) *AccountUserQuotaShareUsageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetWindowKind sets the "window_kind" field.
func (_u *AccountUserQuotaShareUsageUpdate) SetWindowKind(v string) *AccountUserQuotaShareUsageUpdate {
	_u.mutation.SetWindowKind(v)
	return _u
}

// SetNillableWindowKind sets the "window_kind" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdate) SetNillableWindowKind(v *string) *AccountUserQuotaShareUsageUpdate {
	if v != nil {
		_u.SetWindowKind(*v)
	}
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *AccountUserQuotaShareUsageUpdate) SetResetAt(v time.Time) *AccountUserQuotaShareUsageUpdate {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdate) SetNillableResetAt(v *time.Time) *AccountUserQuotaShareUsageUpdate {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// SetCost sets the "cost" field.
func (_u *AccountUserQuotaShareUsageUpdate) SetCost(v float64) *AccountUserQuotaShareUsageUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdate) SetNillableCost(v *float64) *AccountUserQuotaShareUsageUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *AccountUserQuotaShareUsageUpdate) AddCost(v float64) *AccountUserQuotaShareUsageUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountUserQuotaShareUsageUpdate) SetAccount(v *Account) *AccountUserQuotaShareUsageUpdate {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUserQuotaShareUsageUpdate) SetUser(v *User) *AccountUserQuotaShareUsageUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountUserQuotaShareUsageMutation object of the builder.
func (_u *AccountUserQuotaShareUsageUpdate) Mutation() *AccountUserQuotaShareUsageMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountUserQuotaShareUsageUpdate) ClearAccount() *AccountUserQuotaShareUsageUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUserQuotaShareUsageUpdate) ClearUser() *AccountUserQuotaShareUsageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUserQuotaShareUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUserQuotaShareUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUserQuotaShareUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUserQuotaShareUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUserQuotaShareUsageUpdate) check() error {
	if v, ok := _u.mutation.WindowKind(); ok {
		if err := accountuserquotashareusage.WindowKindValidator(v); err != nil {
			return &ValidationError{Name: "window_kind", err: fmt.Errorf(`ent: validator failed for field "AccountUserQuotaShareUsage.window_kind": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountUserQuotaShareUsage.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountUserQuotaShareUsage.user"`)
	}
	return nil
}

func (_u *AccountUserQuotaShareUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountuserquotashareusage.Table, accountuserquotashareusage.Columns, sqlgraph.NewFieldSpec(accountuserquotashareusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WindowKind(); ok {
		_spec.SetField(accountuserquotashareusage.FieldWindowKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(accountuserquotashareusage.FieldResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(accountuserquotashareusage.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(accountuserquotashareusage.FieldCost, field.TypeFloat64, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.AccountTable,
			Columns: []string{accountuserquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.AccountTable,
			Columns: []string{accountuserquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.UserTable,
			Columns: []string{accountuserquotashareusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.UserTable,
			Columns: []string{accountuserquotashareusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountuserquotashareusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUserQuotaShareUsageUpdateOne is the builder for updating a single AccountUserQuotaShareUsage entity.
type AccountUserQuotaShareUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountUserQuotaShareUsageMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetAccountID(v int64) *AccountUserQuotaShareUsageUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetNillableAccountID(v *int64) *AccountUserQuotaShareUsageUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetUserID(v int64) *AccountUserQuotaShareUsageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetNillableUserID(v *int64) *AccountUserQuotaShareUsageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetWindowKind sets the "window_kind" field.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetWindowKind(v string) *AccountUserQuotaShareUsageUpdateOne {
	_u.mutation.SetWindowKind(v)
	return _u
}

// SetNillableWindowKind sets the "window_kind" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetNillableWindowKind(v *string) *AccountUserQuotaShareUsageUpdateOne {
	if v != nil {
		_u.SetWindowKind(*v)
	}
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetResetAt(v time.Time) *AccountUserQuotaShareUsageUpdateOne {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetNillableResetAt(v *time.Time) *AccountUserQuotaShareUsageUpdateOne {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// SetCost sets the "cost" field.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetCost(v float64) *AccountUserQuotaShareUsageUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetNillableCost(v *float64) *AccountUserQuotaShareUsageUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *AccountUserQuotaShareUsageUpdateOne) AddCost(v float64) *AccountUserQuotaShareUsageUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetAccount(v *Account) *AccountUserQuotaShareUsageUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUserQuotaShareUsageUpdateOne) SetUser(v *User) *AccountUserQuotaShareUsageUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountUserQuotaShareUsageMutation object of the builder.
func (_u *AccountUserQuotaShareUsageUpdateOne) Mutation() *AccountUserQuotaShareUsageMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountUserQuotaShareUsageUpdateOne) ClearAccount() *AccountUserQuotaShareUsageUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUserQuotaShareUsageUpdateOne) ClearUser() *AccountUserQuotaShareUsageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AccountUserQuotaShareUsageUpdate builder.
func (_u *AccountUserQuotaShareUsageUpdateOne) Where(ps ...predicate.AccountUserQuotaShareUsage) *AccountUserQuotaShareUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUserQuotaShareUsageUpdateOne) Select(field string, fields ...string) *AccountUserQuotaShareUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountUserQuotaShareUsage entity.
func (_u *AccountUserQuotaShareUsageUpdateOne) Save(ctx context.Context) (*AccountUserQuotaShareUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUserQuotaShareUsageUpdateOne) SaveX(ctx context.Context) *AccountUserQuotaShareUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUserQuotaShareUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUserQuotaShareUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUserQuotaShareUsageUpdateOne) check() error {
	if v, ok := _u.mutation.WindowKind(); ok {
		if err := accountuserquotashareusage.WindowKindValidator(v); err != nil {
			return &ValidationError{Name: "window_kind", err: fmt.Errorf(`ent: validator failed for field "AccountUserQuotaShareUsage.window_kind": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountUserQuotaShareUsage.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountUserQuotaShareUsage.user"`)
	}
	return nil
}

func (_u *AccountUserQuotaShareUsageUpdateOne) sqlSave(ctx context.Context) (_node *AccountUserQuotaShareUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountuserquotashareusage.Table, accountuserquotashareusage.Columns, sqlgraph.NewFieldSpec(accountuserquotashareusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountUserQuotaShareUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountuserquotashareusage.FieldID)
		for _, f := range fields {
			if !accountuserquotashareusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountuserquotashareusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WindowKind(); ok {
		_spec.SetField(accountuserquotashareusage.FieldWindowKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(accountuserquotashareusage.FieldResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(accountuserquotashareusage.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(accountuserquotashareusage.FieldCost, field.TypeFloat64, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.AccountTable,
			Columns: []string{accountuserquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.AccountTable,
			Columns: []string{accountuserquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.UserTable,
			Columns: []string{accountuserquotashareusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashareusage.UserTable,
			Columns: []string{accountuserquotashareusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountUserQuotaShareUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountuserquotashareusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
