// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountuserquotashareusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountUserQuotaShareUsage is the model entity for the AccountUserQuotaShareUsage schema.
type AccountUserQuotaShareUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// WindowKind holds the value of the "window_kind" field.
	WindowKind string `json:"window_kind,omitempty"`
	// ResetAt holds the value of the "reset_at" field.
	ResetAt time.Time `json:"reset_at,omitempty"`
	// Cost holds the value of the "cost" field.
	Cost float64 `json:"cost,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountUserQuotaShareUsageQuery when eager-loading is set.
	Edges        AccountUserQuotaShareUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountUserQuotaShareUsageEdges holds the relations/edges for other nodes in the graph.
type AccountUserQuotaShareUsageEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountUserQuotaShareUsageEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountUserQuotaShareUsageEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountUserQuotaShareUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountuserquotashareusage.FieldCost:
			values[i] = new(sql.NullFloat64)
		case accountuserquotashareusage.FieldID, accountuserquotashareusage.FieldAccountID, accountuserquotashareusage.FieldUserID:
			values[i] = new(sql.NullInt64)
		case accountuserquotashareusage.FieldWindowKind:
			values[i] = new(sql.NullString)
		case accountuserquotashareusage.FieldResetAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountUserQuotaShareUsage fields.
func (_m *AccountUserQuotaShareUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountuserquotashareusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountuserquotashareusage.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountuserquotashareusage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case accountuserquotashareusage.FieldWindowKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field window_kind", values[i])
			} else if value.Valid {
				_m.WindowKind = value.String
			}
		case accountuserquotashareusage.FieldResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reset_at", values[i])
			} else if value.Valid {
				_m.ResetAt = value.Time
			}
		case accountuserquotashareusage.FieldCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost", values[i])
			} else if value.Valid {
				_m.Cost = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountUserQuotaShareUsage.
// This includes values selected through modifiers, order, etc.
func (_m *AccountUserQuotaShareUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountUserQuotaShareUsage entity.
func (_m *AccountUserQuotaShareUsage) QueryAccount() *AccountQuery {
	return NewAccountUserQuotaShareUsageClient(_m.config).QueryAccount(_m)
}

// QueryUser queries the "user" edge of the AccountUserQuotaShareUsage entity.
func (_m *AccountUserQuotaShareUsage) QueryUser() *UserQuery {
	return NewAccountUserQuotaShareUsageClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this AccountUserQuotaShareUsage.
// Note that you need to call AccountUserQuotaShareUsage.Unwrap() before calling this method if this AccountUserQuotaShareUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountUserQuotaShareUsage) Update() *AccountUserQuotaShareUsageUpdateOne {
	return NewAccountUserQuotaShareUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountUserQuotaShareUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountUserQuotaShareUsage) Unwrap() *AccountUserQuotaShareUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountUserQuotaShareUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountUserQuotaShareUsage) String() string {
	var builder strings.Builder
	builder.WriteString("AccountUserQuotaShareUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("window_kind=")
	builder.WriteString(_m.WindowKind)
	builder.WriteString(", ")
	builder.WriteString("reset_at=")
	builder.WriteString(_m.ResetAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cost))
	builder.WriteByte(')')
	return builder.String()
}

// AccountUserQuotaShareUsages is a parsable slice of AccountUserQuotaShareUsage.
type AccountUserQuotaShareUsages []*AccountUserQuotaShareUsage
