// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountuserquotashare"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountUserQuotaShare is the model entity for the AccountUserQuotaShare schema.
type AccountUserQuotaShare struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// FiveHourPercent holds the value of the "five_hour_percent" field.
	FiveHourPercent float64 `json:"five_hour_percent,omitempty"`
	// SevenDayPercent holds the value of the "seven_day_percent" field.
	SevenDayPercent float64 `json:"seven_day_percent,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountUserQuotaShareQuery when eager-loading is set.
	Edges        AccountUserQuotaShareEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountUserQuotaShareEdges holds the relations/edges for other nodes in the graph.
type AccountUserQuotaShareEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountUserQuotaShareEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountUserQuotaShareEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountUserQuotaShare) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountuserquotashare.FieldFiveHourPercent, accountuserquotashare.FieldSevenDayPercent:
			values[i] = new(sql.NullFloat64)
		case accountuserquotashare.FieldID, accountuserquotashare.FieldAccountID, accountuserquotashare.FieldUserID:
			values[i] = new(sql.NullInt64)
		case accountuserquotashare.FieldCreatedAt, accountuserquotashare.FieldUpdatedAt, accountuserquotashare.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountUserQuotaShare fields.
func (_m *AccountUserQuotaShare) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountuserquotashare.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountuserquotashare.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountuserquotashare.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountuserquotashare.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case accountuserquotashare.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountuserquotashare.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case accountuserquotashare.FieldFiveHourPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field five_hour_percent", values[i])
			} else if value.Valid {
				_m.FiveHourPercent = value.Float64
			}
		case accountuserquotashare.FieldSevenDayPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field seven_day_percent", values[i])
			} else if value.Valid {
				_m.SevenDayPercent = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountUserQuotaShare.
// This includes values selected through modifiers, order, etc.
func (_m *AccountUserQuotaShare) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountUserQuotaShare entity.
func (_m *AccountUserQuotaShare) QueryAccount() *AccountQuery {
	return NewAccountUserQuotaShareClient(_m.config).QueryAccount(_m)
}

// QueryUser queries the "user" edge of the AccountUserQuotaShare entity.
func (_m *AccountUserQuotaShare) QueryUser() *UserQuery {
	return NewAccountUserQuotaShareClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this AccountUserQuotaShare.
// Note that you need to call AccountUserQuotaShare.Unwrap() before calling this method if this AccountUserQuotaShare
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountUserQuotaShare) Update() *AccountUserQuotaShareUpdateOne {
	return NewAccountUserQuotaShareClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountUserQuotaShare entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountUserQuotaShare) Unwrap() *AccountUserQuotaShare {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountUserQuotaShare is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountUserQuotaShare) String() string {
	var builder strings.Builder
	builder.WriteString("AccountUserQuotaShare(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("five_hour_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.FiveHourPercent))
	builder.WriteString(", ")
	builder.WriteString("seven_day_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.SevenDayPercent))
	builder.WriteByte(')')
	return builder.String()
}

// AccountUserQuotaShares is a parsable slice of AccountUserQuotaShare.
type AccountUserQuotaShares []*AccountUserQuotaShare
