// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountuserquotashare"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountUserQuotaShareDelete is the builder for deleting a AccountUserQuotaShare entity.
type AccountUserQuotaShareDelete struct {
	config
	hooks    []Hook
	mutation *AccountUserQuotaShareMutation
}

// Where appends a list predicates to the AccountUserQuotaShareDelete builder.
func (_d *AccountUserQuotaShareDelete) Where(ps ...predicate.AccountUserQuotaShare) *AccountUserQuotaShareDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountUserQuotaShareDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountUserQuotaShareDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountUserQuotaShareDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountuserquotashare.Table, sqlgraph.NewFieldSpec(accountuserquotashare.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountUserQuotaShareDeleteOne is the builder for deleting a single AccountUserQuotaShare entity.
type AccountUserQuotaShareDeleteOne struct {
	_d *AccountUserQuotaShareDelete
}

// Where appends a list predicates to the AccountUserQuotaShareDelete builder.
func (_d *AccountUserQuotaShareDeleteOne) Where(ps ...predicate.AccountUserQuotaShare) *AccountUserQuotaShareDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountUserQuotaShareDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountuserquotashare.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountUserQuotaShareDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
