// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountquotashareusage"
)

// AccountQuotaShareUsage is the model entity for the AccountQuotaShareUsage schema.
type AccountQuotaShareUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// WindowKind holds the value of the "window_kind" field.
	WindowKind string `json:"window_kind,omitempty"`
	// ResetAt holds the value of the "reset_at" field.
	ResetAt time.Time `json:"reset_at,omitempty"`
	// Cost holds the value of the "cost" field.
	Cost float64 `json:"cost,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountQuotaShareUsageQuery when eager-loading is set.
	Edges        AccountQuotaShareUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountQuotaShareUsageEdges holds the relations/edges for other nodes in the graph.
type AccountQuotaShareUsageEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountQuotaShareUsageEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountQuotaShareUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountquotashareusage.FieldCost:
			values[i] = new(sql.NullFloat64)
		case accountquotashareusage.FieldID, accountquotashareusage.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case accountquotashareusage.FieldWindowKind:
			values[i] = new(sql.NullString)
		case accountquotashareusage.FieldResetAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountQuotaShareUsage fields.
func (_m *AccountQuotaShareUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountquotashareusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountquotashareusage.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountquotashareusage.FieldWindowKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field window_kind", values[i])
			} else if value.Valid {
				_m.WindowKind = value.String
			}
		case accountquotashareusage.FieldResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reset_at", values[i])
			} else if value.Valid {
				_m.ResetAt = value.Time
			}
		case accountquotashareusage.FieldCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost", values[i])
			} else if value.Valid {
				_m.Cost = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountQuotaShareUsage.
// This includes values selected through modifiers, order, etc.
func (_m *AccountQuotaShareUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountQuotaShareUsage entity.
func (_m *AccountQuotaShareUsage) QueryAccount() *AccountQuery {
	return NewAccountQuotaShareUsageClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this AccountQuotaShareUsage.
// Note that you need to call AccountQuotaShareUsage.Unwrap() before calling this method if this AccountQuotaShareUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountQuotaShareUsage) Update() *AccountQuotaShareUsageUpdateOne {
	return NewAccountQuotaShareUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountQuotaShareUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountQuotaShareUsage) Unwrap() *AccountQuotaShareUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountQuotaShareUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountQuotaShareUsage) String() string {
	var builder strings.Builder
	builder.WriteString("AccountQuotaShareUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("window_kind=")
	builder.WriteString(_m.WindowKind)
	builder.WriteString(", ")
	builder.WriteString("reset_at=")
	builder.WriteString(_m.ResetAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cost))
	builder.WriteByte(')')
	return builder.String()
}

// AccountQuotaShareUsages is a parsable slice of AccountQuotaShareUsage.
type AccountQuotaShareUsages []*AccountQuotaShareUsage
