// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountquotashareusage"
)

// AccountQuotaShareUsageCreate is the builder for creating a AccountQuotaShareUsage entity.
type AccountQuotaShareUsageCreate struct {
	config
	mutation *AccountQuotaShareUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountQuotaShareUsageCreate) SetAccountID(v int64) *AccountQuotaShareUsageCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetWindowKind sets the "window_kind" field.
func (_c *AccountQuotaShareUsageCreate) SetWindowKind(v string) *AccountQuotaShareUsageCreate {
	_c.mutation.SetWindowKind(v)
	return _c
}

// SetResetAt sets the "reset_at" field.
func (_c *AccountQuotaShareUsageCreate) SetResetAt(v time.Time) *AccountQuotaShareUsageCreate {
	_c.mutation.SetResetAt(v)
	return _c
}

// SetCost sets the "cost" field.
func (_c *AccountQuotaShareUsageCreate) SetCost(v float64) *AccountQuotaShareUsageCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *AccountQuotaShareUsageCreate) SetNillableCost(v *float64) *AccountQuotaShareUsageCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountQuotaShareUsageCreate) SetAccount(v *Account) *AccountQuotaShareUsageCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the AccountQuotaShareUsageMutation object of the builder.
func (_c *AccountQuotaShareUsageCreate) Mutation() *AccountQuotaShareUsageMutation {
	return _c.mutation
}

// Save creates the AccountQuotaShareUsage in the database.
func (_c *AccountQuotaShareUsageCreate) Save(ctx context.Context) (*AccountQuotaShareUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountQuotaShareUsageCreate) SaveX(ctx context.Context) *AccountQuotaShareUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountQuotaShareUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountQuotaShareUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountQuotaShareUsageCreate) defaults() {
	if _, ok := _c.mutation.Cost(); !ok {
		v := accountquotashareusage.DefaultCost
		_c.mutation.SetCost(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountQuotaShareUsageCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountQuotaShareUsage.account_id"`)}
	}
	if _, ok := _c.mutation.WindowKind(); !ok {
		return &ValidationError{Name: "window_kind", err: errors.New(`ent: missing required field "AccountQuotaShareUsage.window_kind"`)}
	}
	if v, ok := _c.mutation.WindowKind(); ok {
		if err := accountquotashareusage.WindowKindValidator(v); err != nil {
			return &ValidationError{Name: "window_kind", err: fmt.Errorf(`ent: validator failed for field "AccountQuotaShareUsage.window_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResetAt(); !ok {
		return &ValidationError{Name: "reset_at", err: errors.New(`ent: missing required field "AccountQuotaShareUsage.reset_at"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "AccountQuotaShareUsage.cost"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountQuotaShareUsage.account"`)}
	}
	return nil
}

func (_c *AccountQuotaShareUsageCreate) sqlSave(ctx context.Context) (*AccountQuotaShareUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountQuotaShareUsageCreate) createSpec() (*AccountQuotaShareUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountQuotaShareUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountquotashareusage.Table, sqlgraph.NewFieldSpec(accountquotashareusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.WindowKind(); ok {
		_spec.SetField(accountquotashareusage.FieldWindowKind, field.TypeString, value)
		_node.WindowKind = value
	}
	if value, ok := _c.mutation.ResetAt(); ok {
		_spec.SetField(accountquotashareusage.FieldResetAt, field.TypeTime, value)
		_node.ResetAt = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(accountquotashareusage.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountquotashareusage.AccountTable,
			Columns: []string{accountquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountQuotaShareUsage.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountQuotaShareUsageUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountQuotaShareUsageCreate) OnConflict(opts ...sql.ConflictOption) *AccountQuotaShareUsageUpsertOne {
	_c.conflict = opts
	return &AccountQuotaShareUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountQuotaShareUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountQuotaShareUsageCreate) OnConflictColumns(columns ...string) *AccountQuotaShareUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountQuotaShareUsageUpsertOne{
		create: _c,
	}
}

type (
	// AccountQuotaShareUsageUpsertOne is the builder for "upsert"-ing
	//  one AccountQuotaShareUsage node.
	AccountQuotaShareUsageUpsertOne struct {
		create *AccountQuotaShareUsageCreate
	}

	// AccountQuotaShareUsageUpsert is the "OnConflict" setter.
	AccountQuotaShareUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountQuotaShareUsageUpsert) SetAccountID(v int64) *AccountQuotaShareUsageUpsert {
	u.Set(accountquotashareusage.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsert) UpdateAccountID() *AccountQuotaShareUsageUpsert {
	u.SetExcluded(accountquotashareusage.FieldAccountID)
	return u
}

// SetWindowKind sets the "window_kind" field.
func (u *AccountQuotaShareUsageUpsert) SetWindowKind(v string) *AccountQuotaShareUsageUpsert {
	u.Set(accountquotashareusage.FieldWindowKind, v)
	return u
}

// UpdateWindowKind sets the "window_kind" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsert) UpdateWindowKind() *AccountQuotaShareUsageUpsert {
	u.SetExcluded(accountquotashareusage.FieldWindowKind)
	return u
}

// SetResetAt sets the "reset_at" field.
func (u *AccountQuotaShareUsageUpsert) SetResetAt(v time.Time) *AccountQuotaShareUsageUpsert {
	u.Set(accountquotashareusage.FieldResetAt, v)
	return u
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsert) UpdateResetAt() *AccountQuotaShareUsageUpsert {
	u.SetExcluded(accountquotashareusage.FieldResetAt)
	return u
}

// SetCost sets the "cost" field.
func (u *AccountQuotaShareUsageUpsert) SetCost(v float64) *AccountQuotaShareUsageUpsert {
	u.Set(accountquotashareusage.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsert) UpdateCost() *AccountQuotaShareUsageUpsert {
	u.SetExcluded(accountquotashareusage.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *AccountQuotaShareUsageUpsert) AddCost(v float64) *AccountQuotaShareUsageUpsert {
	u.Add(accountquotashareusage.FieldCost, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountQuotaShareUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountQuotaShareUsageUpsertOne) UpdateNewValues() *AccountQuotaShareUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountQuotaShareUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountQuotaShareUsageUpsertOne) Ignore() *AccountQuotaShareUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountQuotaShareUsageUpsertOne) DoNothing() *AccountQuotaShareUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountQuotaShareUsageCreate.OnConflict
// documentation for more info.
func (u *AccountQuotaShareUsageUpsertOne) Update(set func(*AccountQuotaShareUsageUpsert)) *AccountQuotaShareUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountQuotaShareUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountQuotaShareUsageUpsertOne) SetAccountID(v int64) *AccountQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsertOne) UpdateAccountID() *AccountQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.UpdateAccountID()
	})
}

// SetWindowKind sets the "window_kind" field.
func (u *AccountQuotaShareUsageUpsertOne) SetWindowKind(v string) *AccountQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.SetWindowKind(v)
	})
}

// UpdateWindowKind sets the "window_kind" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsertOne) UpdateWindowKind() *AccountQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.UpdateWindowKind()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *AccountQuotaShareUsageUpsertOne) SetResetAt(v time.Time) *AccountQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsertOne) UpdateResetAt() *AccountQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.UpdateResetAt()
	})
}

// SetCost sets the "cost" field.
func (u *AccountQuotaShareUsageUpsertOne) SetCost(v float64) *AccountQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *AccountQuotaShareUsageUpsertOne) AddCost(v float64) *AccountQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsertOne) UpdateCost() *AccountQuotaShareUsageUpsertOne {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.UpdateCost()
	})
}

// Exec executes the query.
func (u *AccountQuotaShareUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountQuotaShareUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountQuotaShareUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountQuotaShareUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountQuotaShareUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountQuotaShareUsageCreateBulk is the builder for creating many AccountQuotaShareUsage entities in bulk.
type AccountQuotaShareUsageCreateBulk struct {
	config
	err      error
	builders []*AccountQuotaShareUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountQuotaShareUsage entities in the database.
func (_c *AccountQuotaShareUsageCreateBulk) Save(ctx context.Context) ([]*AccountQuotaShareUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountQuotaShareUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountQuotaShareUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountQuotaShareUsageCreateBulk) SaveX(ctx context.Context) []*AccountQuotaShareUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountQuotaShareUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountQuotaShareUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountQuotaShareUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountQuotaShareUsageUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountQuotaShareUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountQuotaShareUsageUpsertBulk {
	_c.conflict = opts
	return &AccountQuotaShareUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountQuotaShareUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountQuotaShareUsageCreateBulk) OnConflictColumns(columns ...string) *AccountQuotaShareUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountQuotaShareUsageUpsertBulk{
		create: _c,
	}
}

// AccountQuotaShareUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountQuotaShareUsage nodes.
type AccountQuotaShareUsageUpsertBulk struct {
	create *AccountQuotaShareUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountQuotaShareUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountQuotaShareUsageUpsertBulk) UpdateNewValues() *AccountQuotaShareUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountQuotaShareUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountQuotaShareUsageUpsertBulk) Ignore() *AccountQuotaShareUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountQuotaShareUsageUpsertBulk) DoNothing() *AccountQuotaShareUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountQuotaShareUsageCreateBulk.OnConflict
// documentation for more info.
func (u *AccountQuotaShareUsageUpsertBulk) Update(set func(*AccountQuotaShareUsageUpsert)) *AccountQuotaShareUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountQuotaShareUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountQuotaShareUsageUpsertBulk) SetAccountID(v int64) *AccountQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsertBulk) UpdateAccountID() *AccountQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.UpdateAccountID()
	})
}

// SetWindowKind sets the "window_kind" field.
func (u *AccountQuotaShareUsageUpsertBulk) SetWindowKind(v string) *AccountQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.SetWindowKind(v)
	})
}

// UpdateWindowKind sets the "window_kind" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsertBulk) UpdateWindowKind() *AccountQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.UpdateWindowKind()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *AccountQuotaShareUsageUpsertBulk) SetResetAt(v time.Time) *AccountQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsertBulk) UpdateResetAt() *AccountQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.UpdateResetAt()
	})
}

// SetCost sets the "cost" field.
func (u *AccountQuotaShareUsageUpsertBulk) SetCost(v float64) *AccountQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *AccountQuotaShareUsageUpsertBulk) AddCost(v float64) *AccountQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *AccountQuotaShareUsageUpsertBulk) UpdateCost() *AccountQuotaShareUsageUpsertBulk {
	return u.Update(func(s *AccountQuotaShareUsageUpsert) {
		s.UpdateCost()
	})
}

// Exec executes the query.
func (u *AccountQuotaShareUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountQuotaShareUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountQuotaShareUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountQuotaShareUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
