// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountquotashareusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountQuotaShareUsageUpdate is the builder for updating AccountQuotaShareUsage entities.
type AccountQuotaShareUsageUpdate struct {
	config
	hooks    []Hook
	mutation *AccountQuotaShareUsageMutation
}

// Where appends a list predicates to the AccountQuotaShareUsageUpdate builder.
func (_u *AccountQuotaShareUsageUpdate) Where(ps ...predicate.AccountQuotaShareUsage) *AccountQuotaShareUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountQuotaShareUsageUpdate) SetAccountID(v int64) *AccountQuotaShareUsageUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountQuotaShareUsageUpdate) SetNillableAccountID(v *int64) *AccountQuotaShareUsageUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetWindowKind sets the "window_kind" field.
func (_u *AccountQuotaShareUsageUpdate) SetWindowKind(v string) *AccountQuotaShareUsageUpdate {
	_u.mutation.SetWindowKind(v)
	return _u
}

// SetNillableWindowKind sets the "window_kind" field if the given value is not nil.
func (_u *AccountQuotaShareUsageUpdate) SetNillableWindowKind(v *string) *AccountQuotaShareUsageUpdate {
	if v != nil {
		_u.SetWindowKind(*v)
	}
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *AccountQuotaShareUsageUpdate) SetResetAt(v time.Time) *AccountQuotaShareUsageUpdate {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *AccountQuotaShareUsageUpdate) SetNillableResetAt(v *time.Time) *AccountQuotaShareUsageUpdate {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// SetCost sets the "cost" field.
func (_u *AccountQuotaShareUsageUpdate) SetCost(v float64) *AccountQuotaShareUsageUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *AccountQuotaShareUsageUpdate) SetNillableCost(v *float64) *AccountQuotaShareUsageUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *AccountQuotaShareUsageUpdate) AddCost(v float64) *AccountQuotaShareUsageUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountQuotaShareUsageUpdate) SetAccount(v *Account) *AccountQuotaShareUsageUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the AccountQuotaShareUsageMutation object of the builder.
func (_u *AccountQuotaShareUsageUpdate) Mutation() *AccountQuotaShareUsageMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountQuotaShareUsageUpdate) ClearAccount() *AccountQuotaShareUsageUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountQuotaShareUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountQuotaShareUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountQuotaShareUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountQuotaShareUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountQuotaShareUsageUpdate) check() error {
	if v, ok := _u.mutation.WindowKind(); ok {
		if err := accountquotashareusage.WindowKindValidator(v); err != nil {
			return &ValidationError{Name: "window_kind", err: fmt.Errorf(`ent: validator failed for field "AccountQuotaShareUsage.window_kind": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountQuotaShareUsage.account"`)
	}
	return nil
}

func (_u *AccountQuotaShareUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountquotashareusage.Table, accountquotashareusage.Columns, sqlgraph.NewFieldSpec(accountquotashareusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WindowKind(); ok {
		_spec.SetField(accountquotashareusage.FieldWindowKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(accountquotashareusage.FieldResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(accountquotashareusage.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(accountquotashareusage.FieldCost, field.TypeFloat64, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountquotashareusage.AccountTable,
			Columns: []string{accountquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountquotashareusage.AccountTable,
			Columns: []string{accountquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountquotashareusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountQuotaShareUsageUpdateOne is the builder for updating a single AccountQuotaShareUsage entity.
type AccountQuotaShareUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountQuotaShareUsageMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountQuotaShareUsageUpdateOne) SetAccountID(v int64) *AccountQuotaShareUsageUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountQuotaShareUsageUpdateOne) SetNillableAccountID(v *int64) *AccountQuotaShareUsageUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetWindowKind sets the "window_kind" field.
func (_u *AccountQuotaShareUsageUpdateOne) SetWindowKind(v string) *AccountQuotaShareUsageUpdateOne {
	_u.mutation.SetWindowKind(v)
	return _u
}

// SetNillableWindowKind sets the "window_kind" field if the given value is not nil.
func (_u *AccountQuotaShareUsageUpdateOne) SetNillableWindowKind(v *string) *AccountQuotaShareUsageUpdateOne {
	if v != nil {
		_u.SetWindowKind(*v)
	}
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *AccountQuotaShareUsageUpdateOne) SetResetAt(v time.Time) *AccountQuotaShareUsageUpdateOne {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *AccountQuotaShareUsageUpdateOne) SetNillableResetAt(v *time.Time) *AccountQuotaShareUsageUpdateOne {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// SetCost sets the "cost" field.
func (_u *AccountQuotaShareUsageUpdateOne) SetCost(v float64) *AccountQuotaShareUsageUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *AccountQuotaShareUsageUpdateOne) SetNillableCost(v *float64) *AccountQuotaShareUsageUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *AccountQuotaShareUsageUpdateOne) AddCost(v float64) *AccountQuotaShareUsageUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountQuotaShareUsageUpdateOne) SetAccount(v *Account) *AccountQuotaShareUsageUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the AccountQuotaShareUsageMutation object of the builder.
func (_u *AccountQuotaShareUsageUpdateOne) Mutation() *AccountQuotaShareUsageMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountQuotaShareUsageUpdateOne) ClearAccount() *AccountQuotaShareUsageUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the AccountQuotaShareUsageUpdate builder.
func (_u *AccountQuotaShareUsageUpdateOne) Where(ps ...predicate.AccountQuotaShareUsage) *AccountQuotaShareUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountQuotaShareUsageUpdateOne) Select(field string, fields ...string) *AccountQuotaShareUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountQuotaShareUsage entity.
func (_u *AccountQuotaShareUsageUpdateOne) Save(ctx context.Context) (*AccountQuotaShareUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountQuotaShareUsageUpdateOne) SaveX(ctx context.Context) *AccountQuotaShareUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountQuotaShareUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountQuotaShareUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountQuotaShareUsageUpdateOne) check() error {
	if v, ok := _u.mutation.WindowKind(); ok {
		if err := accountquotashareusage.WindowKindValidator(v); err != nil {
			return &ValidationError{Name: "window_kind", err: fmt.Errorf(`ent: validator failed for field "AccountQuotaShareUsage.window_kind": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountQuotaShareUsage.account"`)
	}
	return nil
}

func (_u *AccountQuotaShareUsageUpdateOne) sqlSave(ctx context.Context) (_node *AccountQuotaShareUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountquotashareusage.Table, accountquotashareusage.Columns, sqlgraph.NewFieldSpec(accountquotashareusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountQuotaShareUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountquotashareusage.FieldID)
		for _, f := range fields {
			if !accountquotashareusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountquotashareusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WindowKind(); ok {
		_spec.SetField(accountquotashareusage.FieldWindowKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(accountquotashareusage.FieldResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(accountquotashareusage.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(accountquotashareusage.FieldCost, field.TypeFloat64, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountquotashareusage.AccountTable,
			Columns: []string{accountquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountquotashareusage.AccountTable,
			Columns: []string{accountquotashareusage.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountQuotaShareUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountquotashareusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
