// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountuserquotashare"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountUserQuotaShareUpdate is the builder for updating AccountUserQuotaShare entities.
type AccountUserQuotaShareUpdate struct {
	config
	hooks    []Hook
	mutation *AccountUserQuotaShareMutation
}

// Where appends a list predicates to the AccountUserQuotaShareUpdate builder.
func (_u *AccountUserQuotaShareUpdate) Where(ps ...predicate.AccountUserQuotaShare) *AccountUserQuotaShareUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUserQuotaShareUpdate) SetUpdatedAt(v time.Time) *AccountUserQuotaShareUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AccountUserQuotaShareUpdate) SetDeletedAt(v time.Time) *AccountUserQuotaShareUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdate) SetNillableDeletedAt(v *time.Time) *AccountUserQuotaShareUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AccountUserQuotaShareUpdate) ClearDeletedAt() *AccountUserQuotaShareUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUserQuotaShareUpdate) SetAccountID(v int64) *AccountUserQuotaShareUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdate) SetNillableAccountID(v *int64) *AccountUserQuotaShareUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountUserQuotaShareUpdate) SetUserID(v int64) *AccountUserQuotaShareUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdate) SetNillableUserID(v *int64) *AccountUserQuotaShareUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFiveHourPercent sets the "five_hour_percent" field.
func (_u *AccountUserQuotaShareUpdate) SetFiveHourPercent(v float64) *AccountUserQuotaShareUpdate {
	_u.mutation.ResetFiveHourPercent()
	_u.mutation.SetFiveHourPercent(v)
	return _u
}

// SetNillableFiveHourPercent sets the "five_hour_percent" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdate) SetNillableFiveHourPercent(v *float64) *AccountUserQuotaShareUpdate {
	if v != nil {
		_u.SetFiveHourPercent(*v)
	}
	return _u
}

// AddFiveHourPercent adds value to the "five_hour_percent" field.
func (_u *AccountUserQuotaShareUpdate) AddFiveHourPercent(v float64) *AccountUserQuotaShareUpdate {
	_u.mutation.AddFiveHourPercent(v)
	return _u
}

// SetSevenDayPercent sets the "seven_day_percent" field.
func (_u *AccountUserQuotaShareUpdate) SetSevenDayPercent(v float64) *AccountUserQuotaShareUpdate {
	_u.mutation.ResetSevenDayPercent()
	_u.mutation.SetSevenDayPercent(v)
	return _u
}

// SetNillableSevenDayPercent sets the "seven_day_percent" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdate) SetNillableSevenDayPercent(v *float64) *AccountUserQuotaShareUpdate {
	if v != nil {
		_u.SetSevenDayPercent(*v)
	}
	return _u
}

// AddSevenDayPercent adds value to the "seven_day_percent" field.
func (_u *AccountUserQuotaShareUpdate) AddSevenDayPercent(v float64) *AccountUserQuotaShareUpdate {
	_u.mutation.AddSevenDayPercent(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountUserQuotaShareUpdate) SetAccount(v *Account) *AccountUserQuotaShareUpdate {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUserQuotaShareUpdate) SetUser(v *User) *AccountUserQuotaShareUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountUserQuotaShareMutation object of the builder.
func (_u *AccountUserQuotaShareUpdate) Mutation() *AccountUserQuotaShareMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountUserQuotaShareUpdate) ClearAccount() *AccountUserQuotaShareUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUserQuotaShareUpdate) ClearUser() *AccountUserQuotaShareUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUserQuotaShareUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUserQuotaShareUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUserQuotaShareUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUserQuotaShareUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUserQuotaShareUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if accountuserquotashare.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized accountuserquotashare.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := accountuserquotashare.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUserQuotaShareUpdate) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountUserQuotaShare.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountUserQuotaShare.user"`)
	}
	return nil
}

func (_u *AccountUserQuotaShareUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountuserquotashare.Table, accountuserquotashare.Columns, sqlgraph.NewFieldSpec(accountuserquotashare.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountuserquotashare.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(accountuserquotashare.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(accountuserquotashare.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FiveHourPercent(); ok {
		_spec.SetField(accountuserquotashare.FieldFiveHourPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFiveHourPercent(); ok {
		_spec.AddField(accountuserquotashare.FieldFiveHourPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SevenDayPercent(); ok {
		_spec.SetField(accountuserquotashare.FieldSevenDayPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSevenDayPercent(); ok {
		_spec.AddField(accountuserquotashare.FieldSevenDayPercent, field.TypeFloat64, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.AccountTable,
			Columns: []string{accountuserquotashare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.AccountTable,
			Columns: []string{accountuserquotashare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.UserTable,
			Columns: []string{accountuserquotashare.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.UserTable,
			Columns: []string{accountuserquotashare.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountuserquotashare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUserQuotaShareUpdateOne is the builder for updating a single AccountUserQuotaShare entity.
type AccountUserQuotaShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountUserQuotaShareMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUserQuotaShareUpdateOne) SetUpdatedAt(v time.Time) *AccountUserQuotaShareUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AccountUserQuotaShareUpdateOne) SetDeletedAt(v time.Time) *AccountUserQuotaShareUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdateOne) SetNillableDeletedAt(v *time.Time) *AccountUserQuotaShareUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AccountUserQuotaShareUpdateOne) ClearDeletedAt() *AccountUserQuotaShareUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUserQuotaShareUpdateOne) SetAccountID(v int64) *AccountUserQuotaShareUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdateOne) SetNillableAccountID(v *int64) *AccountUserQuotaShareUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountUserQuotaShareUpdateOne) SetUserID(v int64) *AccountUserQuotaShareUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdateOne) SetNillableUserID(v *int64) *AccountUserQuotaShareUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFiveHourPercent sets the "five_hour_percent" field.
func (_u *AccountUserQuotaShareUpdateOne) SetFiveHourPercent(v float64) *AccountUserQuotaShareUpdateOne {
	_u.mutation.ResetFiveHourPercent()
	_u.mutation.SetFiveHourPercent(v)
	return _u
}

// SetNillableFiveHourPercent sets the "five_hour_percent" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdateOne) SetNillableFiveHourPercent(v *float64) *AccountUserQuotaShareUpdateOne {
	if v != nil {
		_u.SetFiveHourPercent(*v)
	}
	return _u
}

// AddFiveHourPercent adds value to the "five_hour_percent" field.
func (_u *AccountUserQuotaShareUpdateOne) AddFiveHourPercent(v float64) *AccountUserQuotaShareUpdateOne {
	_u.mutation.AddFiveHourPercent(v)
	return _u
}

// SetSevenDayPercent sets the "seven_day_percent" field.
func (_u *AccountUserQuotaShareUpdateOne) SetSevenDayPercent(v float64) *AccountUserQuotaShareUpdateOne {
	_u.mutation.ResetSevenDayPercent()
	_u.mutation.SetSevenDayPercent(v)
	return _u
}

// SetNillableSevenDayPercent sets the "seven_day_percent" field if the given value is not nil.
func (_u *AccountUserQuotaShareUpdateOne) SetNillableSevenDayPercent(v *float64) *AccountUserQuotaShareUpdateOne {
	if v != nil {
		_u.SetSevenDayPercent(*v)
	}
	return _u
}

// AddSevenDayPercent adds value to the "seven_day_percent" field.
func (_u *AccountUserQuotaShareUpdateOne) AddSevenDayPercent(v float64) *AccountUserQuotaShareUpdateOne {
	_u.mutation.AddSevenDayPercent(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountUserQuotaShareUpdateOne) SetAccount(v *Account) *AccountUserQuotaShareUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUserQuotaShareUpdateOne) SetUser(v *User) *AccountUserQuotaShareUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountUserQuotaShareMutation object of the builder.
func (_u *AccountUserQuotaShareUpdateOne) Mutation() *AccountUserQuotaShareMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountUserQuotaShareUpdateOne) ClearAccount() *AccountUserQuotaShareUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUserQuotaShareUpdateOne) ClearUser() *AccountUserQuotaShareUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AccountUserQuotaShareUpdate builder.
func (_u *AccountUserQuotaShareUpdateOne) Where(ps ...predicate.AccountUserQuotaShare) *AccountUserQuotaShareUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUserQuotaShareUpdateOne) Select(field string, fields ...string) *AccountUserQuotaShareUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountUserQuotaShare entity.
func (_u *AccountUserQuotaShareUpdateOne) Save(ctx context.Context) (*AccountUserQuotaShare, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUserQuotaShareUpdateOne) SaveX(ctx context.Context) *AccountUserQuotaShare {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUserQuotaShareUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUserQuotaShareUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUserQuotaShareUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if accountuserquotashare.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized accountuserquotashare.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := accountuserquotashare.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUserQuotaShareUpdateOne) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountUserQuotaShare.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountUserQuotaShare.user"`)
	}
	return nil
}

func (_u *AccountUserQuotaShareUpdateOne) sqlSave(ctx context.Context) (_node *AccountUserQuotaShare, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountuserquotashare.Table, accountuserquotashare.Columns, sqlgraph.NewFieldSpec(accountuserquotashare.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountUserQuotaShare.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountuserquotashare.FieldID)
		for _, f := range fields {
			if !accountuserquotashare.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountuserquotashare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountuserquotashare.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(accountuserquotashare.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(accountuserquotashare.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FiveHourPercent(); ok {
		_spec.SetField(accountuserquotashare.FieldFiveHourPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFiveHourPercent(); ok {
		_spec.AddField(accountuserquotashare.FieldFiveHourPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SevenDayPercent(); ok {
		_spec.SetField(accountuserquotashare.FieldSevenDayPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSevenDayPercent(); ok {
		_spec.AddField(accountuserquotashare.FieldSevenDayPercent, field.TypeFloat64, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.AccountTable,
			Columns: []string{accountuserquotashare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.AccountTable,
			Columns: []string{accountuserquotashare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.UserTable,
			Columns: []string{accountuserquotashare.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserquotashare.UserTable,
			Columns: []string{accountuserquotashare.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountUserQuotaShare{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountuserquotashare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
