// Code generated by ent, DO NOT EDIT.

package accountuserquotashare

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldDeletedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldAccountID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldUserID, v))
}

// FiveHourPercent applies equality check predicate on the "five_hour_percent" field. It's identical to FiveHourPercentEQ.
func FiveHourPercent(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldFiveHourPercent, v))
}

// SevenDayPercent applies equality check predicate on the "seven_day_percent" field. It's identical to SevenDayPercentEQ.
func SevenDayPercent(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldSevenDayPercent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNotNull(FieldDeletedAt))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNotIn(FieldAccountID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNotIn(FieldUserID, vs...))
}

// FiveHourPercentEQ applies the EQ predicate on the "five_hour_percent" field.
func FiveHourPercentEQ(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldFiveHourPercent, v))
}

// FiveHourPercentNEQ applies the NEQ predicate on the "five_hour_percent" field.
func FiveHourPercentNEQ(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNEQ(FieldFiveHourPercent, v))
}

// FiveHourPercentIn applies the In predicate on the "five_hour_percent" field.
func FiveHourPercentIn(vs ...float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldIn(FieldFiveHourPercent, vs...))
}

// FiveHourPercentNotIn applies the NotIn predicate on the "five_hour_percent" field.
func FiveHourPercentNotIn(vs ...float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNotIn(FieldFiveHourPercent, vs...))
}

// FiveHourPercentGT applies the GT predicate on the "five_hour_percent" field.
func FiveHourPercentGT(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGT(FieldFiveHourPercent, v))
}

// FiveHourPercentGTE applies the GTE predicate on the "five_hour_percent" field.
func FiveHourPercentGTE(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGTE(FieldFiveHourPercent, v))
}

// FiveHourPercentLT applies the LT predicate on the "five_hour_percent" field.
func FiveHourPercentLT(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLT(FieldFiveHourPercent, v))
}

// FiveHourPercentLTE applies the LTE predicate on the "five_hour_percent" field.
func FiveHourPercentLTE(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLTE(FieldFiveHourPercent, v))
}

// SevenDayPercentEQ applies the EQ predicate on the "seven_day_percent" field.
func SevenDayPercentEQ(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldEQ(FieldSevenDayPercent, v))
}

// SevenDayPercentNEQ applies the NEQ predicate on the "seven_day_percent" field.
func SevenDayPercentNEQ(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNEQ(FieldSevenDayPercent, v))
}

// SevenDayPercentIn applies the In predicate on the "seven_day_percent" field.
func SevenDayPercentIn(vs ...float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldIn(FieldSevenDayPercent, vs...))
}

// SevenDayPercentNotIn applies the NotIn predicate on the "seven_day_percent" field.
func SevenDayPercentNotIn(vs ...float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldNotIn(FieldSevenDayPercent, vs...))
}

// SevenDayPercentGT applies the GT predicate on the "seven_day_percent" field.
func SevenDayPercentGT(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGT(FieldSevenDayPercent, v))
}

// SevenDayPercentGTE applies the GTE predicate on the "seven_day_percent" field.
func SevenDayPercentGTE(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldGTE(FieldSevenDayPercent, v))
}

// SevenDayPercentLT applies the LT predicate on the "seven_day_percent" field.
func SevenDayPercentLT(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLT(FieldSevenDayPercent, v))
}

// SevenDayPercentLTE applies the LTE predicate on the "seven_day_percent" field.
func SevenDayPercentLTE(v float64) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.FieldLTE(FieldSevenDayPercent, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountUserQuotaShare) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountUserQuotaShare) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountUserQuotaShare) predicate.AccountUserQuotaShare {
	return predicate.AccountUserQuotaShare(sql.NotPredicates(p))
}
