// Code generated by ent, DO NOT EDIT.

package accountuserquotashareusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldAccountID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldUserID, v))
}

// WindowKind applies equality check predicate on the "window_kind" field. It's identical to WindowKindEQ.
func WindowKind(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldWindowKind, v))
}

// ResetAt applies equality check predicate on the "reset_at" field. It's identical to ResetAtEQ.
func ResetAt(v time.Time) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldResetAt, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v float64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldCost, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNotIn(FieldAccountID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNotIn(FieldUserID, vs...))
}

// WindowKindEQ applies the EQ predicate on the "window_kind" field.
func WindowKindEQ(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldWindowKind, v))
}

// WindowKindNEQ applies the NEQ predicate on the "window_kind" field.
func WindowKindNEQ(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNEQ(FieldWindowKind, v))
}

// WindowKindIn applies the In predicate on the "window_kind" field.
func WindowKindIn(vs ...string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldIn(FieldWindowKind, vs...))
}

// WindowKindNotIn applies the NotIn predicate on the "window_kind" field.
func WindowKindNotIn(vs ...string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNotIn(FieldWindowKind, vs...))
}

// WindowKindGT applies the GT predicate on the "window_kind" field.
func WindowKindGT(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldGT(FieldWindowKind, v))
}

// WindowKindGTE applies the GTE predicate on the "window_kind" field.
func WindowKindGTE(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldGTE(FieldWindowKind, v))
}

// WindowKindLT applies the LT predicate on the "window_kind" field.
func WindowKindLT(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldLT(FieldWindowKind, v))
}

// WindowKindLTE applies the LTE predicate on the "window_kind" field.
func WindowKindLTE(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldLTE(FieldWindowKind, v))
}

// WindowKindContains applies the Contains predicate on the "window_kind" field.
func WindowKindContains(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldContains(FieldWindowKind, v))
}

// WindowKindHasPrefix applies the HasPrefix predicate on the "window_kind" field.
func WindowKindHasPrefix(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldHasPrefix(FieldWindowKind, v))
}

// WindowKindHasSuffix applies the HasSuffix predicate on the "window_kind" field.
func WindowKindHasSuffix(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldHasSuffix(FieldWindowKind, v))
}

// WindowKindEqualFold applies the EqualFold predicate on the "window_kind" field.
func WindowKindEqualFold(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEqualFold(FieldWindowKind, v))
}

// WindowKindContainsFold applies the ContainsFold predicate on the "window_kind" field.
func WindowKindContainsFold(v string) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldContainsFold(FieldWindowKind, v))
}

// ResetAtEQ applies the EQ predicate on the "reset_at" field.
func ResetAtEQ(v time.Time) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldResetAt, v))
}

// ResetAtNEQ applies the NEQ predicate on the "reset_at" field.
func ResetAtNEQ(v time.Time) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNEQ(FieldResetAt, v))
}

// ResetAtIn applies the In predicate on the "reset_at" field.
func ResetAtIn(vs ...time.Time) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldIn(FieldResetAt, vs...))
}

// ResetAtNotIn applies the NotIn predicate on the "reset_at" field.
func ResetAtNotIn(vs ...time.Time) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNotIn(FieldResetAt, vs...))
}

// ResetAtGT applies the GT predicate on the "reset_at" field.
func ResetAtGT(v time.Time) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldGT(FieldResetAt, v))
}

// ResetAtGTE applies the GTE predicate on the "reset_at" field.
func ResetAtGTE(v time.Time) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldGTE(FieldResetAt, v))
}

// ResetAtLT applies the LT predicate on the "reset_at" field.
func ResetAtLT(v time.Time) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldLT(FieldResetAt, v))
}

// ResetAtLTE applies the LTE predicate on the "reset_at" field.
func ResetAtLTE(v time.Time) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldLTE(FieldResetAt, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v float64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v float64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...float64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...float64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v float64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v float64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v float64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v float64) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.FieldLTE(FieldCost, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountUserQuotaShareUsage) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountUserQuotaShareUsage) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountUserQuotaShareUsage) predicate.AccountUserQuotaShareUsage {
	return predicate.AccountUserQuotaShareUsage(sql.NotPredicates(p))
}
